name: create new city

on:
  workflow_dispatch:
    inputs:
      city_id:
        description: "自治体ID"
        required: true
        type: string
      prefecture:
        description: "都道府県"
        required: true
        type: string
      city_name:
        description: "市区町村"
        required: true
        type: string
      service_name:
        description: "サービス名"
        required: true
        type: string

env:
  template_dir: _template
  crypt_key_length: 32
  password_length: 24
  branch_name: new-${{ inputs.city_id }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      # テンプレートフォルダをコピー
      - name: copy directory
        run: cp -r $template_dir ${{ inputs.city_id }}

      # 同じファイルで sed できないので、一旦別ファイルとして保存する
      # 都道府県 置換
      - name: replace prefecture
        run: sed -e 's/#prefecture#/${{ inputs.prefecture }}/' $template_dir/profile.php > ${{ inputs.city_id }}/profile_1.php

      # 市区町村 置換
      - name: replace city name
        run: sed -e 's/#city-name#/${{ inputs.city_name }}/' ${{ inputs.city_id }}/profile_1.php > ${{ inputs.city_id }}/profile_2.php
        # サービス名 置換
      - name: replace service name
        run: sed -e 's/#service-name#/${{ inputs.service_name }}/' ${{ inputs.city_id }}/profile_2.php > ${{ inputs.city_id }}/profile_3.php

      # crypt-key ランダムで生成 (アルファベット・数値のみ)、置換
      - name: create crypt key
        run: sed -e 's/#crypt-key#/${{ crypt_key }}/' ${{ inputs.city_id }}/profile_3.php > ${{ inputs.city_id }}/profile_4.php
        env:
          crypt_key: cat /dev/urandom | base64 | fold -w 256 | head -n 1 | sed -e 's/[^[0-9a-zA-Z]//g' | fold -w $crypt_key_length | head -n 1

      # DBパスワード ランダムで生成 (アルファベット・数値のみ)、置換
      - name: "db-password"
        run: sed -e 's/#db-password#/${{ password }}/' ${{ inputs.city_id }}/profile_4.php > ${{ inputs.city_id }}/profile.php
        env:
          password: cat /dev/urandom | base64 | fold -w 256 | head -n 1 | sed -e 's/[^[0-9a-zA-Z]//g' | fold -w $password_length | head -n 1

      # 後始末
      - name: tear down
        run: rm profile_1.php profile_2.php profile_3.php profile_4.php

      - name: Create new Branch, commit, push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTION_TOKEN }}
        run: |
          echo $branch_name
          git checkout -b $branch_name
          git add ./${{ inputs.city_id }}/
          git commit -m "新規構築 ${{ inputs.city_name }}"
          git push origin $branch_name

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
