name: create new city

on:
  workflow_dispatch:
    inputs:
      city_id:
        description: "自治体ID"
        required: true
        type: string
      prefecture:
        description: "都道府県"
        required: true
        type: string
      city_name:
        description: "市区町村"
        required: true
        type: string
      service_name:
        description: "サービス名"
        required: true
        type: string
      since:
        description: "サービス開始日"
        required: true
        type: string

env:
  template_dir: _template
  crypt_key_length: 32
  password_length: 24

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      # テンプレートフォルダをコピー
      - name: copy directory
        run: cp -r $template_dir ${{ inputs.city_id }}

      # 同じファイルで sed できないので、一旦別ファイルとして保存する
      # 都道府県 置換
      - name: replace prefecture
        run: sed -e 's/#prefecture#/${{ inputs.prefecture }}/' $template_dir/profile.php > ${{ inputs.city_id }}/profile_1.php

      # 市区町村 置換
      - name: replace city name
        run: sed -e 's/#city-name#/${{ inputs.city_name }}/' ${{ inputs.city_id }}/profile_1.php > ${{ inputs.city_id }}/profile_2.php

      # サービス名 置換
      - name: replace service name
        run: sed -e 's/#service-name#/${{ inputs.service_name }}/' ${{ inputs.city_id }}/profile_2.php > ${{ inputs.city_id }}/profile_3.php

      # サービス開始日 置換
      - name: replace since
        run: |
          since=`echo "${{ inputs.since }}" | sed -e "s/\//\\\\\//g"`
          sed -e 's/#since#/$since/' ${{ inputs.city_id }}/profile_3.php > ${{ inputs.city_id }}/profile_4.php

      # crypt-key ランダムで生成 (アルファベット・数値のみ)、置換
      - name: create crypt key
        run: |
          crypt_key=`cat /dev/urandom | base64 | fold -w 256 | head -n 1 | sed -e 's/[^[0-9a-zA-Z]//g' | fold -w $crypt_key_length | head -n 1``
          echo $crypt_key
          sed -e "s/#crypt-key#/$crypt_key/" ${{ inputs.city_id }}/profile_4.php > ${{ inputs.city_id }}/profile_5.php

      # DBパスワード ランダムで生成 (アルファベット・数値のみ)、置換
      - name: "db-password"
        run: |
          password=`cat /dev/urandom | base64 | fold -w 256 | head -n 1 | sed -e 's/[^[0-9a-zA-Z]//g' | fold -w $password_length | head -n 1``
          echo $password
          sed -e "s/#db-password#/$password/" ${{ inputs.city_id }}/profile_5.php > ${{ inputs.city_id }}/profile_6.php

      # Copy Right
      - name: copy right
        run: |
          copy_right=`echo "${{ inputs.city_id }}" | awk -F '-' '{ for(i=1; i<=NF; i++) {printf toupper(substr($i,1,1)) substr($i,2) " " }} END {print ""}'`
          echo $copy_right
          sed -e "s/#copy-right#/$copy_right/" ${{ inputs.city_id }}/profile_6.php > ${{ inputs.city_id }}/profile.php

      # 後始末
      - name: tear down
        run: rm ${{ inputs.city_id }}/profile_1.php ${{ inputs.city_id }}/profile_2.php ${{ inputs.city_id }}/profile_3.php ${{ inputs.city_id }}/profile_4.php ${{ inputs.city_id }}/profile_5.php ${{ inputs.city_id }}/profile_6.php

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          committer: "Atsuko Kurosawa<a-kurosawa@mi-labo.co.jp>"
          commit-message: "新規構築 ${{ inputs.city_name }}"
          title: "新規構築 ${{ inputs.city_name }}"
          body: "auto: 新規構築 ${{ inputs.city_name }}"
          branch: "new-${{ inputs.city_id }}"
